title: Some Deadlines
description: Countdowns to some academic conference deadlines
author: Yanju Chen

# comment out for local debugging
# domain: "ucsb.edu"
# baseurl: "https://sites.cs.ucsb.edu/~yanju/deadlines"

twitter_hashtag: iffyanju
github_username: chyanju
github_repo: some-deadlines

markdown: kramdown
# ga_id: G-G350W8SSRE

include: ['_pages']
