title: AI Conference Deadlines
description: Countdowns to top CV/NLP/ML/Robotics/AI conference deadlines
author: Abhishek Das

domain: "ucsb.edu"
baseurl: "https://sites.cs.ucsb.edu/~yanju/deadlines"

twitter_hashtag: machinelearning
github_username: paperswithcode
github_repo: ai-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
